# global
url: https://www.steamcmd.net
title: SteamCMD API

# env specific
api_url: https://api.steamcmd.net/v1/info/740
vue_url: https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js

# build
sass:
  style: compressed

exclude: [".scss", "README.md", "docker-compose.yml", "node_modules", "gruntfile.js", "package.json", "Gemfile", "Gemfile.lock", "LICENSE"]
