version: '3'
services:
  web:
    image: "jguyomard/hugo-builder:latest"
    ports:
      - "1313:1313"
    volumes:
      - ./:/src
    user: hugo
    command: hugo serve -D --bind="0.0.0.0"
  cors:
    image: "imjacobclark/cors-container:latest"
    ports:
      - "3000:3000"
